version: "3"
services:
  challenge:
    container_name: challenge
    image: challenge
    build:
      context: .
      target: challenge
    command: sh -c "geth -dev -http -http.addr 0.0.0.0 & socat TCP-LISTEN:1337,reuseaddr,fork exec:'python3 -u challenge/challenge.py'"
    expose:
      - 1337
      - 8545
    ports:
      - "1337:1337"
      - "8545:8545"
