services:
  challenge:
    build:
      context: .
    working_dir: /home/ctf/challenge
    command: sh -c "python3 proxy.py & python3 challenge.py"
    expose:
      - 1337
      - 8545
    ports:
      - "1337:1337"
      - "8545:8545"
